import type { EvidenceItem } from "../domain/evidence";
import type { PillarScores } from "../domain/scoring";

export const therapyPillarScores: PillarScores = {
  demand: 64,
  pain: 82,
  momentum: 58,
  competitionFit: 66,
  activity: 49,
  channelFit: 72,
  evidenceQuality: 61,
};

export const therapyEvidenceSeed: EvidenceItem[] = [
  {
    id: "therapist-paperwork-reddit",
    source: "Reddit",
    sourceType: "post",
    date: "2026-05-08",
    query: "therapist paperwork",
    snippet: "Private-practice therapists discussing documentation spilling into evenings.",
    link: "https://www.reddit.com/",
    metricContribution: "Pain",
    included: true,
    reason: "Direct pain language and matching audience.",
    duplicateCluster: "therapy-paperwork-1",
    signalStrength: 82,
  },
  {
    id: "soap-notes-youtube",
    source: "YouTube",
    sourceType: "video",
    date: "2026-04-18",
    query: "SOAP notes",
    snippet: "Tutorial demand around writing faster SOAP notes.",
    link: "https://www.youtube.com/",
    metricContribution: "Demand",
    included: true,
    reason: "Searchable education demand around the workflow.",
    duplicateCluster: "soap-notes-1",
    signalStrength: 64,
  },
  {
    id: "therapy-launch-producthunt",
    source: "Product Hunt",
    sourceType: "launch",
    date: "2026-03-21",
    query: "therapy notes app",
    snippet: "A recent launch for clinical note workflow automation.",
    link: "https://www.producthunt.com/",
    metricContribution: "Competition Fit",
    included: true,
    reason: "Comparable product supply signal.",
    duplicateCluster: "therapy-launch-1",
    signalStrength: 66,
  },
  {
    id: "privacy-therapy-hn",
    source: "Hacker News",
    sourceType: "comment",
    date: "2026-02-16",
    query: "privacy therapy notes",
    snippet: "Discussion of privacy concerns around assisted clinical documentation.",
    link: "https://news.ycombinator.com/",
    metricContribution: "Evidence Quality",
    included: true,
    reason: "Relevant privacy objection for adoption risk.",
    duplicateCluster: "privacy-therapy-1",
    signalStrength: 61,
  },
  {
    id: "documentation-stack-question",
    source: "Stack Exchange",
    sourceType: "question",
    date: "2026-01-12",
    query: "mental health notes",
    snippet: "Question around structured documentation practices.",
    link: "https://stackexchange.com/",
    metricContribution: "Channel Fit",
    included: true,
    reason: "Professional workflow question with matching terminology.",
    duplicateCluster: "documentation-question-1",
    signalStrength: 72,
  },
  {
    id: "ehr-notes-github",
    source: "GitHub",
    sourceType: "repo",
    date: "2026-04-02",
    query: "EHR notes",
    snippet: "Open-source clinical documentation experiments with slow recent activity.",
    link: "https://github.com/",
    metricContribution: "Activity",
    included: true,
    reason: "Builder activity signal around adjacent documentation tools.",
    duplicateCluster: "ehr-notes-1",
    signalStrength: 49,
  },
  {
    id: "session-notes-reddit",
    source: "Reddit",
    sourceType: "comment",
    date: "2026-05-11",
    query: "session notes",
    snippet: "Solo clinician describes a workaround for drafting notes after appointments.",
    link: "https://www.reddit.com/",
    metricContribution: "Pain",
    included: true,
    reason: "Workaround behavior and matching audience.",
    duplicateCluster: "session-notes-workaround-1",
    signalStrength: 80,
  },
  {
    id: "soap-note-template-youtube",
    source: "YouTube",
    sourceType: "video",
    date: "2026-03-05",
    query: "SOAP note template",
    snippet: "Creator tutorial showing repeated search demand for structured note templates.",
    link: "https://www.youtube.com/",
    metricContribution: "Demand",
    included: true,
    reason: "Template/tutorial signal supports demand pillar.",
    duplicateCluster: "soap-template-1",
    signalStrength: 62,
  },
  {
    id: "clinical-ai-launch",
    source: "Product Hunt",
    sourceType: "launch",
    date: "2026-02-27",
    query: "clinical AI notes",
    snippet: "Launch comments discuss privacy-safe AI notes for healthcare teams.",
    link: "https://www.producthunt.com/",
    metricContribution: "Momentum",
    included: true,
    reason: "Recent launch signal with adoption objections.",
    duplicateCluster: "clinical-ai-launch-1",
    signalStrength: 58,
  },
  {
    id: "documentation-burden-hn",
    source: "Hacker News",
    sourceType: "comment",
    date: "2026-04-29",
    query: "clinical documentation burden",
    snippet: "Clinicians discussing documentation load as a drag on care time.",
    link: "https://news.ycombinator.com/",
    metricContribution: "Pain",
    included: true,
    reason: "Adjacent professional pain signal.",
    duplicateCluster: "documentation-burden-1",
    signalStrength: 78,
  },
  {
    id: "clinical-notes-github",
    source: "GitHub",
    sourceType: "repo",
    date: "2026-03-30",
    query: "clinical notes automation",
    snippet: "Repository activity around structured clinical note workflows.",
    link: "https://github.com/",
    metricContribution: "Activity",
    included: true,
    reason: "Recent builder activity in adjacent note automation space.",
    duplicateCluster: "clinical-notes-repo-1",
    signalStrength: 51,
  },
  {
    id: "physical-therapy-notes",
    source: "Reddit",
    sourceType: "post",
    date: "2026-05-02",
    query: "therapy notes",
    snippet: "Physical therapy treatment notes workflow discussion.",
    link: "https://www.reddit.com/",
    metricContribution: "Demand",
    included: true,
    reason: "Seed inclusion before query-bundle filtering.",
    duplicateCluster: "physical-therapy-notes-1",
    signalStrength: 24,
  },
];
